kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: simplelb
subjects:
- kind: ServiceAccount
  name: simplelb
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: simplelb
  apiGroup: rbac.authorization.k8s.io
